import { Property } from '@/types/property';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'ib-1',
    codigo: 'IB-101',
    titulo: 'Casa Moderna com Área Gourmet no Jardim Coopagro',
    descricao: 'Linda residência com projeto contemporâneo no Jardim Coopagro em Toledo. Possui 3 quartos (sendo 1 suíte com closet), sala com pé-direito elevado, cozinha integrando à área gourmet com churrasqueira e acabamento em porcelanato de grande formato. Amplo quintal nos fundos com espaço para instalação de piscina.',
    tipo: 'venda',
    categoria: 'casa',
    preco: 790000,
    rua: 'Rua das Camélias',
    bairro: 'Jardim Coopagro',
    cidade: 'Toledo',
    estado: 'PR',
    quartos: 3,
    banheiros: 2,
    vagas: 2,
    areaTotal: 300,
    areaUtil: 165,
    imagens: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80'
    ],
    comodidades: ['Suíte com Closet', 'Espaço Gourmet com Churrasqueira', 'Pé-direito Elevado', 'Porcelanato Polido', 'Portão Eletrônico', 'Iluminação em LED', 'Tubulação para Ar-condicionado'],
    status: 'disponivel',
    destaque: true,
    createdAt: '2024-06-10T00:00:00.000Z',
    updatedAt: '2024-06-10T00:00:00.000Z',
  },
  {
    id: 'ib-2',
    codigo: 'IB-102',
    titulo: 'Sobrado Elegante no Loteamento Brisa do Lago',
    descricao: 'Excelente sobrado de alto padrão arquitetônico no prestigiado Loteamento Brisa do Lago. Vista privilegiada, 3 suítes aconchegantes no pavimento superior com persianas integradas automatizadas, living amplo para dois ambientes, cozinha planejada e quintal privativo.',
    tipo: 'venda',
    categoria: 'sobrado',
    preco: 1150000,
    rua: 'Rua Beira Lago',
    bairro: 'Loteamento Brisa do Lago',
    cidade: 'Toledo',
    estado: 'PR',
    quartos: 3,
    banheiros: 4,
    vagas: 2,
    areaTotal: 360,
    areaUtil: 235,
    imagens: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80'
    ],
    comodidades: ['3 Suítes Plenas', 'Área Gourmet Completa', 'Esquadrias em Alumínio', 'Tubulação para Água Quente', 'Acabamento em Gesso', 'Garagem Paralela Coberta'],
    status: 'disponivel',
    destaque: true,
    createdAt: '2024-06-15T00:00:00.000Z',
    updatedAt: '2024-06-15T00:00:00.000Z',
  },
  {
    id: 'ib-3',
    codigo: 'IB-103',
    titulo: 'Casa Térrea Aconchegante no Bairro Cristo Rei',
    descricao: 'Residência perfeita para quem busca praticidade e conforto no Bairro Cristo Rei. Conta com 2 quartos, sala de estar integrada, cozinha com bancada em granito, lavanderia coberta e vaga para veículos. Pronta para financiamento habitacional.',
    tipo: 'venda',
    categoria: 'casa',
    preco: 430000,
    rua: 'Rua São Judas Tadeu',
    bairro: 'Cristo Rei',
    cidade: 'Toledo',
    estado: 'PR',
    quartos: 2,
    banheiros: 1,
    vagas: 2,
    areaTotal: 180,
    areaUtil: 88,
    imagens: [
      'https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80'
    ],
    comodidades: ['Financiável Minha Casa Minha Vida', 'Piso Cerâmico de Qualidade', 'Bancadas em Granito', 'Espaço nos Fundos', 'Muros e Portão Instalados'],
    status: 'disponivel',
    destaque: true,
    createdAt: '2024-07-01T00:00:00.000Z',
    updatedAt: '2024-07-01T00:00:00.000Z',
  },
  {
    id: 'ib-4',
    codigo: 'IB-104',
    titulo: 'Terreno Plano Pronto para Construir no Jardim Santa Maria',
    descricao: 'Excelente lote residencial em localização consolidada no Jardim Santa Maria em Toledo. Topografia plana, ótima orientação solar, rua asfaltada e toda infraestrutura de água, luz e esgoto. Ideal para projetos residenciais térreos ou sobrados.',
    tipo: 'venda',
    categoria: 'terreno',
    preco: 280000,
    rua: 'Rua Almirante Tamandaré',
    bairro: 'Jardim Santa Maria',
    cidade: 'Toledo',
    estado: 'PR',
    quartos: 0,
    banheiros: 0,
    vagas: 0,
    areaTotal: 360,
    areaUtil: 360,
    imagens: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80'
    ],
    comodidades: ['Topografia Plana', 'Documentação 100% Regularizada', 'Pronto para Construir', 'Asfalto e Infraestrutura Completa', 'Excelente Insolação'],
    status: 'disponivel',
    destaque: false,
    createdAt: '2024-07-12T00:00:00.000Z',
    updatedAt: '2024-07-12T00:00:00.000Z',
  },
  {
    id: 'ib-5',
    codigo: 'IB-105',
    titulo: 'Apartamento com Sacada Gourmet no Centro',
    descricao: 'Apartamento aconchegante e bem iluminado no Centro de Toledo. Possui 1 suíte + 1 quarto, sacada ampla com churrasqueira a carvão, sala de jantar e estar integradas. Edifício com elevador e salão de festas decorado.',
    tipo: 'venda',
    categoria: 'apartamento',
    preco: 560000,
    rua: 'Rua Santos Dumont',
    bairro: 'Centro',
    cidade: 'Toledo',
    estado: 'PR',
    quartos: 2,
    banheiros: 2,
    vagas: 1,
    areaTotal: 110,
    areaUtil: 82,
    imagens: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'
    ],
    comodidades: ['Sacada com Churrasqueira', 'Elevador', 'Salão de Festas', 'Portaria Eletrônica', 'Móveis Fixos na Cozinha'],
    status: 'disponivel',
    destaque: true,
    createdAt: '2024-08-01T00:00:00.000Z',
    updatedAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'ib-6',
    codigo: 'IB-106',
    titulo: 'Chácara de Lazer e Descanso Próximo ao Centro',
    descricao: 'Propriedade rural encantadora a poucos minutos da área urbana de Toledo. Perfeita para momentos inesquecíveis em família: casa sede aconchegante, piscina com deck de madeira, pomar produtivo com árvores frutíferas e quiosque com churrasqueira rústica.',
    tipo: 'venda',
    categoria: 'rural',
    preco: 850000,
    rua: 'Estrada da Pedreira',
    bairro: 'Tocantins',
    cidade: 'Toledo',
    estado: 'PR',
    quartos: 3,
    banheiros: 2,
    vagas: 6,
    areaTotal: 4800,
    areaUtil: 140,
    imagens: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80'
    ],
    comodidades: ['Piscina com Deck', 'Quiosque Gourmet', 'Pomar Formado', 'Poço Artesiano', 'Energia Elétrica Bifásica', 'Área Verde Preservada'],
    status: 'disponivel',
    destaque: false,
    createdAt: '2024-08-20T00:00:00.000Z',
    updatedAt: '2024-08-20T00:00:00.000Z',
  }
];
